[module]

# Mount Partial
[[module.mounts]]
source = "partials"
target = "layouts/partials/fontawesome"

# FontAwesome Icons
[[module.imports]]
path="github.com/FortAwesome/Font-Awesome"
[[module.imports.mounts]]
source = "svgs"
target = "assets/fontawesome"